### ISSUE TITLE
Questions to Martin

### ISSUE THREAD

**Issue by beepy0** [beepy0/thesis#32]
- [x] 1. How rapid does streaming data arrive in real use-cases? Does it make sense to load all data in RAM first or just read it sequentially from a file-pointer (might be too slow)? 
- [x] 2. About data generators - I don't see any seeding options in the data generators provided by the sketches source code, so I need to use a different one. Do you have any generator in mind or can I just create the data using python and load it (read question 1.) before I run the sketches? Since the data itself won't have to change from run to run, this could also work?
- [x] 3. Would you prefer a specific data distribution for the tests? Normal, Zipfian, etc?
- [x] 4. Would the distribution impact the throughput at all? Should I test for that?
- [x] 5. Which aspects of the algorithms am I benchmarking? `sketch update` only, or also `join size`, `self-join size` ?
- [x] 6. Is there a way to interpret the resulting self_join sizes to make sure the algorithms are working as they should? I have seeded the I1 and I2 variables to make sure they are consistent between runs and the data vectors are also constant, but I don't know how to work with the end result other than comparing the number between the baseline and optimized versions later on.
- [x] 6-extra. I found the Fast-AGMS algorithm to be better-to-significantly-better in approximating the size - AGMS seemed a lot more sensitive to the right ratio between vector size and input data size (it worked best for zipf but other distributions like discrete normal were off by a factor of 4-5 from the target result). I want to discuss this with you to cancel out any suspicion of bugs in the implementation. **TODO**: compare a couple of results to make sure the numbers are okay.
- [x] 7. *Sorry if this question isn't clear enough:* I have noticed that AGMS's throughput is sensitive to the amount of independent variables, since the whole vector gets updated for each new value (in the code I have `bins_no` and `rows_no` and all `bins_no * rows_no` get updated for each new value) whereas Fast-AGMS isn't. Should I include a diagram showing AGMS's comparative disadvantage in that regard, as part of a discussion subsection for example?
- [x] 8. Since the source code doesn't provide an H3-family hash function (there are only a 2-wise CW2 and 4-wise CW4 b-valued random variables according to the author, which I cannot fully understand so far.), I remember you mentioned they are quite common. I am having a hard time googling for an implementation, or was the plan that I implement it myself? All I need is a boolean matrix and the function from the paper you emailed me (https://www.cise.ufl.edu/~adobra/Publications/tods-2007-06.pdf), right?
- [x] 9. The resulting value after hashing with H3 can be of any length I choose (currently 32bit). You mentioned that modulo operations for such functions slow down the algorithm, so how do I make sure the resulting value only goes up to `buckets_no`? The other bucket hash functions in the project used a modulo at the end for the return value, and currently the H3 implementation also.
- [x] 10. **Discuss in person** : For example, it's not possible to draw a normal distribution of size 100k with a range between the inputs greater than 100k, right? But AGMS will not play nice with sets that are greater than 1 million inputs for example(due to rows_no and buckets_no being > 100 each, to make it more accurate), so I can't do much in that case. I can however do what you suggested for the uniform distribution, but still it's worth discussing in more detail when we meet.
- [x] 11. The SIMD libraries I found support the basic operators such as `+,-,&,^` etc. But what about math functions like `ceil(), lo2()` etc? Same issue when I have to pass the values of a vector of size n to n simultaneous update functions, how does that look like? Do I rewrite the functions to pass the SIMD vectors instead of single variables?
- [x] 12. Do I have to do a presentation? If yes, roughly when? Details?
- [x] 13. Does it make sense to show a snippet of the alternative H3 from this ticket, as to provide the reader with a second option and also make a reference to the other work (if present in any work)?
- [x] 14. Any sense to have performance numbers in a diagram for AVX-2, as a side note?
- [x] 15. Do you have any specific profiling settings you need me to run via VTune? The ones I plan to use initially are: `Advanced Hotspots`, `Microarchitecture Exploration`, `Memory Access`
- [ ] 16. Note down the different comparison approaches Martin said to discuss directly.

**Comment by martinkiefer** [comment]
1. If we are talking actual streaming use cases: Via the network, usually Ethernet. If we are talking about processing resting data in a single-pass fashion: Some storage medium (HDD, SSD) or in-memory. For your thesis, you can assume that the data is already in memory.
2. You are free to use Python to generate the data.
3. Zipfian or discretized values from a normal distribution are both valid choices. I'd go with the Zipfian for now.
4. Interesting question. It could, because of caching. If you keep processing the same value all the time, you are going to hit L1 all the time. It might make sense to do experiments with a uniform distribution as well as a kind of worst-case analysis. 
5. sketch update is enough.

**Comment by beepy0** [comment]
@martinkiefer Could you please answer the new questions above, the ones that don't have a checkmark?
Particularly important for me right now is 8., since I put this as part of the current milestone, which is supposed to go until today :).
I can extend it a bit but I'd rather have this sorted somewhat soon, so I can move to the next milestone.

**Comment by martinkiefer** [comment]
6. There are interpretations besides the size of a self-join. A self-join is the same as the l2 norm that contains the frequencies of the individual values. Or, if you combine two different sketches, you get the join size. If you want to make sure your implementation works correctly, it's probably easiest, if you just generate a  data set with a Zipfian or any other distribution that is significantly skewed. Then you compare the actual self-join size to the estimated one. If you increase the size of the matrix / vector, the accuracy you should converge to the actual join size.

**Comment by martinkiefer** [comment]
7. I think if you mention that when introducing the two algorithms you should be good. The disadvantage will probably show in your evaluation anyway. No need for an extra graph besides the ones in the evaluation.

**Comment by martinkiefer** [comment]
8. If they didn't implement it, you'll have to it on your own. You can try the others as well, if you want to, but H3 would be really important to me. Yes, the matrix and the function from the paper are enough. You should be able to easily map this to bit operators. I can give you the implementation in ScotchDSL from my current project:

v is a 32 Bit vector ( the input value)
seed is a 1024 Bit vector (the flattened boolean matrix)
& is a bitwise and
^ is a bitwise xor
expand(x,y) creates a bit vector of size y with all bits being x
t{1-5}[i] are auxilliary variables
offset is the result

```
for i in 0 to 31 {
    t1[i] <= expand(v(i),32) & seed((i+1)*32-1 downto i*32);
}

for i in 0 to 15 {
    t2[i] <= t1[i] ^ t1[i+16] ;
}

for i in 0 to 7{
    t3[i] <= t2[i] ^ t2[i+8] ;
}

for i in 0 to 3{
    t4[i] <= t3[i] ^ t3[i+4] ;
}

for i in 0 to 1{
    t5[i] <= t4[i] ^ t4[i+2] ;
}

offset <= t5[0] ^ t5[1] ;
```

Essentially, it's a binary reduction you are seeing there in the loops. Note that this is compiled to hardware and not to a computer program so you probably don't want to do it exactly like that.

**Comment by beepy0** [comment]
About question 6, I have used a method to calculate the self join size manually and compared it as you suggested - I will leave an extra note as a question when we meet since I found the Fast-AGMS algorithm to be better-to-significantly-better in approximating the size - AGMS seemed a lot more sensitive to the right ratio between vector size and input data size (it worked best for zipf but other distributions like discrete normal were off by a factor of 4-5 from the target result). I want to discuss this with you to cancel out any suspicion of bugs in the implementation.

**Comment by beepy0** [comment]
I am sorry I already had a different approach for H3 in mind, so I went for that, but stumbled upon something you mentioned and wanted to ask if you have an idea on how to handle it without rewriting the whole function.

**The question**: _The resulting value after hashing with H3 can be of any length I choose (currently 32bit). You mentioned that modulo operations for such functions slow down the algorithm, so how do I make sure the resulting value only goes up to buckets_no? The other bucket hash functions in the project used a modulo at the end for the return value, and currently the H3 implementation also._

`q_matrix` can be seen as a 32x32 matrix. It is an array of size 32, each index can be seen as a row of a matrix, and each value in it has 32bit length.

![Screenshot from 2019-06-09 21-53-59](https://user-images.githubusercontent.com/41326034/59163409-24321180-8b01-11e9-8eef-ca013b0bcbde.png)


I go by this explanation of H3 (source: "Efficient Hardware Hashing Functions for High Performance Computers"), which is more or less the same one you mentioned early as part of the resources email (date is 12.03.19):
![Screenshot from 2019-06-09 21-56-54](https://user-images.githubusercontent.com/41326034/59163441-a15d8680-8b01-11e9-9c88-f1fac45d6e59.png)

**Comment by martinkiefer** [comment]
> About question 6, I have used a method to calculate the self join size manually and compared it as you suggested - I will leave an extra note as a question when we meet since I found the Fast-AGMS algorithm to be better-to-significantly-better in approximating the size - AGMS seemed a lot more sensitive to the right ratio between vector size and input data size (it worked best for zipf but other distributions like discrete normal were off by a factor of 4-5 from the target result). I want to discuss this with you to cancel out any suspicion of bugs in the implementation.

I am not very surprised. Of course, we are updating significantly fewer buckets for Fast AGMS, but the fact that we are using a hash function to decide for a bucket in a row has another interesting effect: Essentially, we are partitioning the data. Take a Zipfian distribution: You have very few values that appear very frequently and a whole lot of distinct values that do not contribute a lot to the join-self join. By this partitioning you are essentially separating the heavy hitters from the noise. And that improves the estimate.

**Comment by martinkiefer** [comment]
> I am sorry I already had a different approach for H3 in mind, so I went for that, but stumbled upon something you mentioned and wanted to ask if you have an idea on how to handle it without rewriting the whole function.
> 
> **The question**: _The resulting value after hashing with H3 can be of any length I choose (currently 32bit). You mentioned that modulo operations for such functions slow down the algorithm, so how do I make sure the resulting value only goes up to buckets_no? The other bucket hash functions in the project used a modulo at the end for the return value, and currently the H3 implementation also._
> 
> `q_matrix` can be seen as a 32x32 matrix. It is an array of size 32, each index can be seen as a row of a matrix, and each value in it has 32bit length.
> 
> ![Screenshot from 2019-06-09 21-53-59](https://user-images.githubusercontent.com/41326034/59163409-24321180-8b01-11e9-8eef-ca013b0bcbde.png)
> 
> I go by this explanation of H3 (source: "Efficient Hardware Hashing Functions for High Performance Computers"), which is more or less the same one you mentioned early as part of the resources email (date is 12.03.19):
> ![Screenshot from 2019-06-09 21-56-54](https://user-images.githubusercontent.com/41326034/59163441-a15d8680-8b01-11e9-9c88-f1fac45d6e59.png)

There's not a lot you can do. 
Exceptions:
- The modulo is cheap if buckets_no is a power of two and if that's known at compile time.
- If you know that buckets_no does only fit once into the maximum value the seed can take, you can work with integer subtraction.
But those are very special cases and I would just go for the modulo. We can think about this later if it turns out to be an actual problem.

Your code has a conditional at the moment. That may save you a load on the key matrix, but the CPU always fetches full cache lines, so you are only saving if 8 consecutive bits are zero. Besides that, this may cause branch misspredictions and pipeline flushes. Those are quite expensive, too. So, if you encounter these problems or the conditional causes trouble when moving to SIMD, you may want to consider an implementation without conditionals (e.g. using software predication or something in the direction of my implementation.)

**Comment by beepy0** [comment]
AGMS/Fast-AGMS: vector size vs. actual throughput graph. Check what happens with SIMD after that
H3 : could vectorize computation for a single value instead of multiple inputs.

**Comment by bpdentolo** [comment]
fixed vars

**Comment by beepy0** [comment]
plot for relative acc/throughput for Fast-AGMS based on rows/buckets size ratio

**Comment by beepy0** [comment]
Chart experiments and make diagrams in advance so you understand the test before you get the actual values.

**Comment by beepy0** [comment]
boost for cross-platform random vars and all other useful stuff

**Comment by beepy0** [comment]
throughput as num inputs/sec or even mb/sec
